# Generated by Django 6.0 on 2026-02-13 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voyage',
            options={'ordering': ['departure_date']},
        ),
        migrations.AddField(
            model_name='voyage',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_transit', 'In Transit'), ('delayed', 'Delayed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operator', 'Operator'), ('analyst', 'Analyst'), ('admin', 'Admin')], default='operator', max_length=20),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='current_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vessels', to='api.port'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_destination', to='api.port'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_origin', to='api.port'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='api.vessel'),
        ),
    ]
