# Generated by Django 6.0 on 2026-02-13 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_voyage_options_voyage_status_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='voyage',
            options={},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='is_read',
        ),
        migrations.RemoveField(
            model_name='port',
            name='location',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='status',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Departure', 'Departure'), ('Arrival', 'Arrival'), ('Delay', 'Delay')], default='DEPARTURE', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='port',
            name='country',
            field=models.CharField(default='India', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('operator', 'Operator')], default='operator', max_length=20),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vessel_type',
            field=models.CharField(choices=[('Cargo', 'Cargo'), ('Tanker', 'Tanker'), ('Passenger', 'Passenger')], max_length=50),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='api.port'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='api.port'),
        ),
    ]
