# Generated by Django 6.0 on 2026-02-13 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_event_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
