# Generated by Django 6.0 on 2026-02-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_voyage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='port',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vessel',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vessel',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
