# Generated by Django 6.0 on 2026-02-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_port_latitude_port_longitude_vessel_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
