# Generated by Django 6.0 on 2026-03-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_vessel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_event_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
